### ISSUE TITLE
[Feat]: What about having custom properties while banning user

### ISSUE THREAD

**Issue by mepsd** [mchev/banhammer#1]
### What happened?

I was wondering if there was a way to set custom properties while banning a user; I know there is a comment field for that, but it would be great if we could save the activity, limit API requests, or prevent access to data that the user shouldn't be seeing; all of these things could be options where they could pass these custom properties and see whenever they review.

### How to reproduce the bug

NA

### Package Version

1.1

### PHP Version

8.1

### Laravel Version

10

### Which operating systems does with happen with?

Linux

**Comment by mepsd** [comment]
Sorry about creating this discussion as bug there was not tag option available for feature

**Comment by mchev** [comment]
How would you like to see this feature work?

```
$user->ban([
 'options' => array('limit' => 10)
]);
```

and then

`$limit = $user->bans()->latest()->options->limit;`

I may have misunderstood the idea, feel free to give me examples of how it should work.

**Comment by mepsd** [comment]
it should be something like
`Ban::create([
 'ip'=>$ips, 'custom_properties'=>$custom_properties]);
`
that will be a json field, and we may construct a variety of utility functions and scopes depending on that.
I'm kind of close to finishing the version; if you give me a day, you'll have PR for it. Just have a look, and if you like it, keep it or continue the discussion in this ticket.

**Comment by mchev** [comment]
Done with #3 
Thanks @mepsd

**Comment by mepsd** [comment]
This weekend i will add some test cases. What do you say?
Do you have any new feature in mind we can workout?

**Comment by mchev** [comment]
I think the package is already doing the job it is asked to do. No need to add new features for the moment. But it is always possible to go further on the tests and refactor some things that can be.
