### ISSUE TITLE
[feature request]: Expiration date for banned IPs

### ISSUE THREAD

**Issue by olivierbaudouin** [mchev/banhammer#10]
### What happened?

Is it possible to add expiration date for banned IPs?

### How to reproduce the bug

Is it possible to add expiration date for banned IPs?

### Package Version

last

### PHP Version

8.1

### Laravel Version

10

### Which operating systems does with happen with?

Linux

**Comment by mchev** [comment]
It is possible to set an expiration date if the banned IP is associated with a model. Is that what you're looking for? 

```php
$model->ban([
	'ip' => "8.8.8.8",
	'expired_at' => now()->addDays(7),
]);
```

Otherwise, indeed, on the IP class, it's not possible to define an expiration date. It's a good idea for a future version.

**Comment by olivierbaudouin** [comment]
Yes, for a future version, it would be cool. Thanks.

**Comment by mchev** [comment]
Done in [v2.1.0](https://github.com/mchev/banhammer/releases/tag/v2.1.0)
