### ISSUE TITLE
Support UUIDs (or publish migrations)

### ISSUE THREAD

**Issue by xtfer** [mchev/banhammer#11]
Our system uses UUIDs, and the current migrations dont support it. We're left with the choice of running a second migration to fix the first one, or forking the package.

Having UUID support would be great, but if thats not possible then publishing the migrations instead of loading them would provide the necessary level of customisability.

**Comment by mchev** [comment]
Hi, and sorry for the delayed response. I'm currently tied up with other tasks, but I'd really love to see this feature implemented. If anyone is interested in contributing, please feel free to submit a PR; I'll review it promptly. Otherwise, it seems like this will need to wait until summer.
