### ISSUE TITLE
Add configurable Model 

### ISSUE THREAD

**Issue by rahmanramsi** [mchev/banhammer#13]
Some package usually allow to modify the Model that the package is use. This will allow user to add some functionality to package model, for example adding a cache layer.

**Comment by mchev** [comment]
Hi,

Thank you for your message. To clarify, you already have the option to extend the `Mchev\Banhammer\Ban` model if you wish to add further functionality. Additionally, I want to confirm that banned IPs are currently cached, although there may be room for improvement in this aspect.

If you have any enhancements or alternative solutions in mind, please don't hesitate to submit a pull request. I'll be sure to review it promptly.
