### ISSUE TITLE
$user->ban();   Not Working

### ISSUE THREAD

**Issue by shakil-dhanga** [mchev/banhammer#5]
### What happened?

use the library then error

### How to reproduce the bug

// My code 
Route::get('/ban-user', function () {

   $user = User::findOrFail(1);
   $user->ban();

});

// Error 

 $user->ban();

Call to undefined method App\Models\User::ban()

### Package Version

2.0

### PHP Version

8.0.26

### Laravel Version

9.19

**Comment by mchev** [comment]
On your User Model do you use the trait `Mchev\Banhammer\Traits\Bannable`

```php
use Mchev\Banhammer\Traits\Bannable;

class User extends Authenticatable
{
    use Bannable;
}
```
