### ISSUE TITLE
[Bug]: N+1 Query when checking model is banned 

### ISSUE THREAD

**Issue by rahmanramsi** [mchev/banhammer#8]
### What happened?

Checking model is banned while looping on list make N+1 Query even the relationship is eager loaded.

### How to reproduce the bug

```php
$users = User::with(['bans'])->get();
foreach ($users as $user) {
    $user->isBanned();
}
```

### Package Version

1.2.0

### PHP Version

8.2.6

### Laravel Version

10.13.2

### Which operating systems does with happen with?

macOS

**Comment by mchev** [comment]
Thanks @rahmanramsi 
Fixed in [v1.2.1](https://github.com/mchev/banhammer/tree/v1.2.1)
